### ISSUE TITLE
Can't override variables between imports

### ISSUE THREAD

**Issue by jgthms** [postcss/postcss-import#177]
Let's say I have 3 files:

**variables.css**
```
$primary: blue;
```

**mixins.css**
```
@define-mixin hero {
  background: $primary;
}
```

**style.css**
```
@import "variables";
@import "mixins";

.hero {
  @mixin hero;
}
```

Let's say, for theming reasons, I want to **override** my variable, like this:
**style.css**
```
@import "variables";
$primary: red;
@import "mixins";

.hero {
  @mixin hero;
}
```

This throws an error:
```
style.css
2:1 ⚠  @import must precede all other statements (besides @charset) [postcss-import]
```

But it is a legitimate reason to include other statements between imports. There are probably other use cases as well.

This bug has been introduced in 8.0.0, when the `parse-statements.js` file has been created.

**Comment by MoOx** [comment]
It's because this plugin aims to stick to w3c specifications. Warnings introduced in 8.0 are considered as an improvement.
You are currently using non valid CSS so you can't blame us :)

Maybe if you succeed to make this behavior optional (disabled by default) via an PR that brings the option covered by tests, we can merge this (as a minor release).

**Comment by jgthms** [comment]
Fair enough.

I guess I'll change my code to match what [Mozilla's docs](https://developer.mozilla.org/en/docs/Web/CSS/@import) suggest:

```
@import url("fineprint.css") print;
@import url("bluish.css") projection, tv;
@import 'custom.css';
```

**Comment by TrySound** [comment]
@jgthms This case works correctly in 8.
