### ISSUE TITLE
Sync mode?

### ISSUE THREAD

**Issue by jedrichards** [postcss/postcss-import#180]
I'm wondering why sync mode was removed in #107?

I'm using `postcss-import` as part of a CSS Modules based stack. If I want to run CSS Modules in a Node or unit test environment (say pre-compiling for ava tests) I need to use [css-modules-require-hook](https://github.com/css-modules/css-modules-require-hook) which is afaiu only able to operate on sync postcss plugins. There's an issue about it here:

https://github.com/css-modules/css-modules-require-hook/issues/58

Async mode by default sounds groovy, but how about re-adding a sync mode in as an option? Or was it removed for specific reasons?

**Comment by TrySound** [comment]
@jedrichards No way. Postcss plugins should be async only (where it's possible). require-hook should be able to support both.

**Comment by jedrichards** [comment]
> require-hook should be able to support both

As far as I understand it the CSS Modules require-hook can't support async plugins because the `require` function itself must be synchronous. E.g. when I do,

```js
var styles = require('./index.css')
```

in a non-bundled Node environment that must return synchronously ... maybe they'll have some ideas over at `css-modules-require-hook` ...

**Comment by MoOx** [comment]
@jedrichards I currently use https://github.com/istarkov/babel-plugin-webpack-loaders to run webpack code sync in my node env (I use ava too).

**Comment by jedrichards** [comment]
@MoOx Thanks! :+1:

**Comment by jrajav** [comment]
In our project, we've found that babel-plugin-webpack-loaders is extremely slow on any project larger than a few files, since it actually runs a separate instance of webpack for each file. Css-modules-require-hook or something similar is really the only option to run postcss in a speedy unit test setup - a pre-build process is way overkill.

This plugin does nothing that actually *needs* to be asynchronous at all, and there is a perfectly valid use case for using it in a synchronous way here - namely, it's not possible to run asynchronous code as a part of a require hook. Is it really worthwhile to enforce a "religious" opinion here when that won't force css-modules-require-hook to change, since it cannot due to the nature of Node.js?

**Comment by MoOx** [comment]
You can use postcss-import v7. It offers a sync mode. v8 will be removed soon anyway (since nobody maintains it, I will revert to v7, which I made and is simpler to understand for me)

**Comment by razor-x** [comment]
@MoOx Since v9 is released, does it include a sync mode or are we stuck on v7 forever? This issue is still relevant for universal apps doing server-side rendering via something like https://github.com/michalkvasnicak/babel-plugin-css-modules-transform.

**Comment by MoOx** [comment]
I am not the maintainer anymore. Ask @RyanZim :)

**Comment by RyanZim** [comment]
@razor-x v9 does not include sync mode, was not aware of this issue. Not sure if this is something worth adding; will try to think about it sometime. I'm going to be crazy busy until after Christmas, so not sure when I'll get a chance to dig into this. If I don't comment here by the new year, please ping me.

**Comment by RyanZim** [comment]
Adding a sync mode would require a total rewrite; I personally don't see this happening.

FWIW, postcss-import doesn't have the best history of playing well with css modules in other ways (since it requires imports to be at the top).

**Comment by longlho** [comment]
@razor-x @jrajav @jedrichards take a look at #293

**Comment by Danetag** [comment]
Any update on this one? I would love to use `postcss-import` but seems to work only in async mode :(

**Comment by TrySound** [comment]
@Danetag It was discussed a lot of times. And no.

**Comment by Danetag** [comment]
Ok thanks!

**Comment by longlho** [comment]
@Danetag https://www.npmjs.com/package/postcss-import-sync2

**Comment by ekilah** [comment]
for what it's worth, here's another plugin that doesn't work in async mode: https://github.com/mrmckeb/typescript-plugin-css-modules

the reason is that the TypeScript language server doesn't support async plugin results.

I am using @longlho 's https://www.npmjs.com/package/postcss-import-sync2 to get around this too. Wanted to share on this fairly old post to help people googling for this issue, and also to show that even 5 years later there are still reasons in the community that we can't always use the async modes, for better or worse.
