### ISSUE TITLE
Importing remote sources

### ISSUE THREAD

**Issue by falafeljan** [postcss/postcss-import#182]
Did you consider inlining of remote source files (http://...) instead of just inlining local files? [`postcss-import-url`](https://github.com/unlight/postcss-import-url) already does what I'm considering.

It would somehow break the concept of inlining files before applying e.g. linting, especially if you're importing vendor files (like `yui-reset`, in my case). This also opposes the approach of using webpack or npm for vendor file management, at least as long as sources are available in such packages.

Anyway, it would be nice to have this feature IMO. A local file cache with expiration time could speed up build times without having developers think about downloading/caching remote files themselves.

What do you think about it?

(Edit: Mistakenly assumed Bower was supported)

**Comment by MoOx** [comment]
Bower can be supported by using one option.

Not a bad idea. PR welcome.

Note: lint should be made on source file, not transformed output.

**Comment by fallafeljan** [comment]
Neat, I'll look into it.

Regarding your note: The first note in the Readme says: “This plugin should probably be used as the first plugin of your list. (...).” I see your point, but when using vendor files one might run into issues, especially when using linters, since they might follow each their own formatting. This is the same when using vendor files over HTTP, therefore my comment on this.

**Comment by MoOx** [comment]
I think linting is the exception of this rule.

**Comment by fallafeljan** [comment]
I'm d'accord with that. :checkered_flag:

**Comment by RyanZim** [comment]
Don't know if we'll ever do that or not, for now, use https://github.com/unlight/postcss-import-url

**Comment by RyanZim** [comment]
Closing as wontfix
