### ISSUE TITLE
Better docs about glob and other ext features

### ISSUE THREAD

**Issue by ai** [postcss/postcss-import#183]
People still can’t info how to use `*.css` and ask it Gitter.

I think all node.js community should stop to think only about internal API and should think about end-user experience and working just out-of-box.

**Comment by MoOx** [comment]
I added a reference to https://github.com/trysound/postcss-easy-import which is what people probably want.

**Comment by in-in** [comment]
Sorry for the silly question, but I still do not understand. You guys add each file manually?

**Comment by MoOx** [comment]
Yes, exactly like when I import a js file.
Nobody does `require('node_modules/*")`.

You are probably using some legacy methodology that consist of having all your css files in a single folder and you import all those files in a some simple entry points.
I am currently (like some other people) using a component based approach, so I require/import each needed css files in the place where they are required.

**Comment by in-in** [comment]
![css](https://cloud.githubusercontent.com/assets/8797432/13550829/7d985a38-e337-11e5-8c6d-79fb1a177cbf.png)

As you can see in the screenshot, my project is split into blocks. And I want to add all .css from the `blocks` directory. For the Jade, I do import manually, because it is very bad at compile time. But PostCSS is much faster.

What is the point to manually add all files from `helpers` directory (variables, reset, etc), as they all do I need?

Maybe I'm doing something wrong.

**Comment by MoOx** [comment]
> What is the point to manually add all files from helpers directory (variables, reset, etc), as they all do I need?

Being explicit? If someone delete a file, you will notice anything during compilation :)

> Maybe I'm doing something wrong.

No, you are just working using a "classic" workflow (which is kind of legacy to me).

I currently use JS only and import just single CSS in some JS (react) component. I do not have "global" CSS (so I very rarely use postcss-import now, which is why you should not listen to me ^^).

**Comment by MoOx** [comment]
Anyway, I prefer to be explicit, so I never "globbed" CSS files.

**Comment by oleersoy** [comment]
@in-in You may also want to consider a project development structure like this:
https://www.npmjs.com/package/superfly-css-pli

This type of structure maintains resources of a given type in a src and corresponding target directory (Built resources).  The idea is to move resources from one folder to another per build step.  So for example:
src/main/css/hello.css > target/main/css/hello.css (Built version) > optimized/main/css/hellos.css (Optimized version)

**Comment by marcustisater** [comment]
Sorry for stepping on any toes here but I'm not a big fan of the decision of removing glob. 

It's very common for users to end up with multiple css files and importing them through one entire stylesheet. I know that for a fact when people use naming conventions like BEM and end up with 30-40 css files. That's shit if you ask me but we are still there and it's not legacy yet, therefor it's nice for the user to have the globbing import option instead of having to add css files every time there is a new one.

I would love to see this ported back. @in-in you can back a few versions, I have done this for some projects.

**Comment by MoOx** [comment]
@marcustisater with the rewrite to make the core better an less buggy, we introduced a mechanism more easy to use any resolve method you want. That's why I can only recommend postcss-easy-import (which, I repeat, use is an easy wrapper plugin) to easily use glob.

**Comment by marcustisater** [comment]
Gotcha, yeah forward to [postcss-easy-import](https://github.com/trysound/postcss-easy-import) sounds good to me.
