### ISSUE TITLE
@import should stay on top of file

### ISSUE THREAD

**Issue by fibo** [postcss/postcss-import#227]
Hi,

thank you very much for postcss-import, it's amazing!

I just wanted to report that, for a newbie (like me :), it should be documented somewhere to put all imports on top of the file.

I tryed at first with an import at the bottom of the file and I got error

<img width="888" alt="screen shot 2016-08-17 at 14 27 05" src="https://cloud.githubusercontent.com/assets/176730/17736193/b44149ca-6486-11e6-97ab-e56749ff5dfc.png">

**Comment by javivelasco** [comment]
I think this should be documented too. Anyway I want to ask, if the purpose of the plugin is to replace content, why should we make the import only on top?

**Comment by MoOx** [comment]
Because it's the spec, and this plugin only transform spec compliant code.
But indeed this error should be clear. It was in v7. v8 is a mess, but #210...

**Comment by longlho** [comment]
@MoOx u should make v7 the active one in `npm` can hose v8 honestly. It's so buggy >.<

**Comment by 1j01** [comment]
What about code like this?
```sass
$color: #FFA600;
$secondary-color: #FFAFED;
$background-color: #230213;
@import "./retro-base.css";
```
The variables have to go before the import because they're referenced in `retro-base.css` and `postcss-advanced-variables` doesn't use a recursive dependency solver or anything fancy like that.

I've worked around this and/or #223 by downgrading to v7. `npm i postcss-import@7.x --save-dev`
