### ISSUE TITLE
onImport argument includes top-level (importing) file

### ISSUE THREAD

**Issue by jmm** [postcss/postcss-import#234]
Hello,

With postcss@5.2.5 and postcss-import@8.1.2 I'm getting the top level file that's passed to postcss in the argument to `onImport`, which is not what I expect. It's documented as:

> array of imported files

Which I interpet as: the files referenced by `@import` rules.

So say I have 2 files like this:

`top-level.css`

``` css
@import "./imported.css";
```

`imported.css`

``` css
/* */
```

In `onImport` I get an array containing the paths for both files.

Is that intentional? If so, can you please document it. And if that's the case, can you commit to it always being the first element in the array?

Thanks!

**Comment by RyanZim** [comment]
@MoOx Related: postcss-cli needs to know which file is the parent of the import.

postcss-cli formerly relied on the (undocumented) fact that inside `onImport`, `this.from` was the parent. This is no longer so. https://github.com/postcss/postcss-cli/issues/44

Either the parent must be guaranteed to be the first element, or `onImport` should receive a second argument `parent`. If we go with the first option, the current implementation would have to be changed since `Object.keys()` technically isn't guaranteed to be deterministic.

**Comment by RyanZim** [comment]
X-ref: https://github.com/postcss/postcss-import/issues/233

**Comment by RyanZim** [comment]
@jmm We added a `dependency` message for each import in https://github.com/postcss/postcss-import/pull/241. This was released as https://github.com/postcss/postcss-import/releases/tag/8.2.0.

You can access the messages by filtering `result.messages`:

```js
var postcss = require('postcss');
postcss([ require('postcss-import') ])
    .process(css, { from: 'src/app.css', to: 'app.css' })
    .then(function (result) {

        // Get list of imports:
        var imports = result.messages.filter(message => message.type === 'dependency')

        // Write File...
    });
```

`imports` would be an array of objects, each with this form:

```js
{
  type: 'dependency',
  file: 'ImportedFile.css',
  parent: 'FileContainingTheImport.css',
}
```

In the future, I might deprecate or remove `onImport`. For now, I think I'll just leave things as they are and recommend using the `dependency` message instead.
