### ISSUE TITLE
@import statements at the bottom (or not at the top)

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-import#257]
**PostCSS Import Version**: 9.0.0
**Node Version**: 7.2.1
**NPM Version**: 4.0.3

I love the new version of PostCSS Import. Thanks for all your hard work.

`@import` statements are being removed but not replaced when they are not placed at the top of the file. Is there documentation surrounding this? Related, is there (or should there be) a `loose` option to allow import statements elsewhere in the file?

**Comment by RyanZim** [comment]
@jonathantneal It's refreshing to get such a well-formed bug report. Thanks!

> `@import` statements are being removed but not replaced when they are not placed at the top of the file.

This module follows the CSS spec, so `@import`s not at the top are invalid. However, it should raise a postcss warning when an invalid statement is encountered. What postcss runner are you using? Try adding https://github.com/postcss/postcss-reporter to the end of your plugin list.

> Is there documentation surrounding this?

From the readme:

> This plugin attempts to follow the CSS `@import` spec; `@import` statements must precede all other statements (besides `@charset`).

Whether invalid `@import`s should be removed is debatable, I personally don't really care.

---

> Is there (or should there be) a loose option to allow import statements elsewhere in the file?

There is not. I have considered adding it, but IIRC, @TrySound says it's not possible due to our support for media query imports. I need to look into this further. If it's not possible, I think the postcss ecosystem needs a canonical plugin for importing files from anywhere; I would consider linking to postcss-partial-import.

**Comment by jonathantneal** [comment]
> What postcss runner are you using?

I am (effectively) using `require('postcss-import').process(CSS_STRING, PROCESS_PLUGIN_AND_OPTIONS)` stand-alone for testing purposes right now.

> I would consider linking to postcss-partial-import.

The next version of postcss-partial-import will rely on postcss-import, because it’s just so great. By keeping a stored copy of `require('postcss-import/lib/resolve-id')`, I can easily implement sugar methods, such as `prefix`, `extension`,  `glob`, or `touch` (generates a nest import if it does not exist). I’m just about finished, in fact.

> I need to look into this further.

Very well. Moving forward, I, too, will honor the rule that "*import statements must precede all other statements*". Otherwise, I’m never going to update partial-import, and I want your superior resolver, and I need my sugar methods.

**Comment by RyanZim** [comment]
@jonathantneal Gotcha!

**Comment by jonathantneal** [comment]
@RyanZim, FWIW, postcss-partial-import has been updated, supporting all the aforementioned sugars https://github.com/jonathantneal/postcss-partial-import

**Comment by TrySound** [comment]
@jonathantneal So you do the same as easy-import? Then I can deprecate it.

**Comment by Avol-V** [comment]
But what about import from somewhere? In some specific builds it can be only one solution, or in other hand I must to run several postcss instances.

**Comment by TrySound** [comment]
You are always able to use less and sass. They are not spec followers.

**Comment by RyanZim** [comment]
@Avol-V @TrySound If there is enough demand for imports in the middle of files, someone will eventually write a postcss plugin for it. That's just how open-source works.

---

@jonathantneal If you have any questions during the rewrite of partal-import, feel free to open a new issue.

**Comment by Avol-V** [comment]
I can write such plugin and I will do this, when there is no other import plugin now in postcss.
Just seems to me more appropriate to extend this plugin, adding optional ability to import from anywhere and without the support of media queries in this case (if it is causing the problem).

**Comment by TrySound** [comment]
Too much cases will make this plugin unsupportable again. Better create simplest thing for your cases which will not have media support,

**Comment by RyanZim** [comment]
I agree with @TrySound.

If it makes more sense, I would consider splitting some sections (like `lib/resolveId`) into separate modules so that they can be used by all import plugins. I'm not sure if the rest of the team is with me on this, just an idea.

@Avol-V If you write such a plugin, please open an issue here; I would consider linking to it.

**Comment by jonathantneal** [comment]
Look at [`postcss-partial-import`’s dependencies](https://github.com/jonathantneal/postcss-partial-import/blob/master/package.json#L24-L27). It uses `postcss-import` for [itself, `postcss`, and `resolve-id`](https://github.com/jonathantneal/postcss-partial-import/blob/master/index.js#L2-L4)

We don’t need another library to extend postcss-import. However, someone may want to look into the issue with resolving imports below the top and adding a `loose` option to this plugin.

As a writer of an alternative import plugin, I’m pretty sure we are trying to get away from that now.

**Comment by TrySound** [comment]
@jonathantneal 
`"node": ">=6.9.1"` is too strict, don't you think?

**Comment by jonathantneal** [comment]
@TrySound, it *should* be v6.9.2, but not because of features. I chose this because it is the [current LTS for Node](https://github.com/nodejs/LTS#lts-schedule). The older popular release (v0.12) ended support 8 months ago, with the last maintenance on it is scheduled to finish in 2 weeks.

All 20+ of my PostCSS plugins now require the current Node LTS, and it has greatly improved their readability and maintainability. If you know a better way to do this, please share.
