### ISSUE TITLE
Optimization by file content must skip "proxy" files

### ISSUE THREAD

**Issue by kud** [postcss/postcss-import#31]
I've a main css file where I do:

```css
@import "module-a";
@import "module-b";
```

Both modules have an `index.css` with `@import "./src/styles/index.css";`

If I compile, it only imports the first module, not the second. For instance, if I switch from `a` to `b` like that:

```css
@import "module-b";
@import "module-a";
```

`module-b` will be imported but not `module-a`.

To fix it, I have to do that:

```css
@import "module-a/src/styles/index.css";
@import "module-b/src/styles/index.css";
```

I'm inspecting this bug but if you have already an idea why, I'll be glad to hear.

**Comment by MoOx** [comment]
This related to the latest release.
@magsout this seems related to the hash feature. If both file contains the exact same thing (just `@import "./src/styles/index.css";`, the current hash optimization skip the 2nd file.
We need to improve by adding a smart strategy to avoid hashing on certain conditions:
- if a file contains only imports directives, we can assume it's a proxy. Lot of people are doing that.

I don't really see other use case since I think as soon as we got others rules than import we can check if the file as already been imported.

I will see if instead of using a hash on the file content, we can make hash from a parsed postcss tree.

**Comment by magsout** [comment]
>@magsout this seems related to the hash feature. If both file contains the exact same thing (just @import "./src/styles/index.css";, the current hash optimization skip the 2nd file.

Oh yes, I hadn't thought about this case.

>if a file contains only imports directives, we can assume it's a proxy. Lot of people are doing that.

Best way to test that.
