### ISSUE TITLE
something like `@import (reference)` from Less?

### ISSUE THREAD

**Issue by deepsweet** [postcss/postcss-import#32]
hi.

is it possible to have this http://lesscss.org/features/#import-options-reference functionality?

for example I want to import `vars.css` file that contains only vars declarations to 100 other css files without inlining but using it as a reference to resolve vars.

**Comment by MoOx** [comment]
If you use postcss-custom-props, you wont have any vars declaration remaning in the output. I don't see the need for that.

**Comment by deepsweet** [comment]
CSS4 custom props syntax is ugly as hell :( I'm talking about https://github.com/postcss/postcss-simple-vars or something.

**Comment by ai** [comment]
@deepsweet do you want to write your own plugin for this case? It is very easy.

I saw two API:

```
@import-part .selector "path/to/file.css";
```

```
@filter .selector {
    @import "path/to/file.css";
}
```

I prefer second API, because:

1. `postcss-import` is a big plugin with many logic inside. Copy all of its code is not a good idea.
2. `@filter` at-rule is more flexile way, which van be used in many cases.
3. UNIX-way :D

**Comment by MoOx** [comment]
I think what you need is just to use this plugin before any others.

**Comment by deepsweet** [comment]
@ai thanks, I'll take a look at plugins API.

**Comment by MoOx** [comment]
postcss-simple-vars don't produce any specific output, so you vars.css should not produce anything.
You just need to use postcss-import before any other plugin + import your vars.css before other imports.
