### ISSUE TITLE
Remote imports are not moved to the top of the output

### ISSUE THREAD

**Issue by bitwhiz** [postcss/postcss-import#424]
Under the **Notes** section in the document, it says "Imports which are not modified (by options.filter or because they are remote imports) are moved to the top of the output." I am not seeing this happen. 

Example:
```
div {
 @import "https://fonts.googleapis.com/css?family=Open+Sans:400,600";
}
```
Expected:
```
 @import "https://fonts.googleapis.com/css?family=Open+Sans:400,600";
div{}
```
Actual:
```
div {
 @import "https://fonts.googleapis.com/css?family=Open+Sans:400,600";
}
```
Do I have the wrong expectation or is this not working as it's supposed to?

**Comment by RyanZim** [comment]
According to CSS spec; `@import` statements must be at the top of a file. `postcss-import` is spec-compliant, so it ignores your import, since it's not at the top. In your example, no spec-compliant browser should load that import statement anyhow.

---

This is what it's referring to:

Input: 
```css
@import "sanitize.css";
@import "./some/local/file.css";
@import "https://fonts.googleapis.com/css?family=Open+Sans:400,600";
```

Output: 
```css
@import "https://fonts.googleapis.com/css?family=Open+Sans:400,600";
/* contents of "sanitize.css" ... */
/* contents of  "./some/local/file.css" ... */
```

This way, the output is still spec-compliant, your import statement is at the top, so the browser will still load your font.

Hope that's clear; let me know if you have any questions.

**Comment by bitwhiz** [comment]
@RyanZim Ah, I see. This is a sass file. I was using sass to process this file before postcss. Sass helped me move these nested remote imports to top of the output. I thought postcss-import would do something similar. Thanks for clarifying!

**Comment by RyanZim** [comment]
Sure, no problem. Yeah, you'll need to have these imports at the top of the file. Worth noting, they don't need to be at the top of the main entry point, they can be at the top of an imported file; they'll still be at the top of the output.
