### ISSUE TITLE
Use the dedicated PostCSS API for errors

### ISSUE THREAD

**Issue by binyamin** [postcss/postcss-import#518]
PostCSS has [a dedicated API method for errors](https://github.com/postcss/postcss/blob/main/docs/guidelines/plugin.md#41-use-nodeerror-on-css-relevant-errors). This codebase is inconsistent. It only uses it in `lib/assign-layer-names.js`.

For example:
https://github.com/postcss/postcss-import/blob/b7d19392756a5e233933d1de5e05938665ac09a4/lib/resolve-id.js#L35-L39
Also:
https://github.com/postcss/postcss-import/blob/b7d19392756a5e233933d1de5e05938665ac09a4/index.js#L261-L265

**Comment by binyamin** [comment]
Also, can I make the code use async functions, instead of using `Promise`? It might be easier to read.

**Comment by RyanZim** [comment]
Good call on the error API; PR welcome.

As for `async`: I agree it would be an improvement; I just never got the time to devote to a full codebase refactor. I'm also unsure how good our test coverage is at the moment, we should probably get some coverage measurement in first and make sure that's in tip-top shape before attempting an `async` refactor. If you want to take it on, more power to you!

I'm unsure if I want to migrate to ESM right away; since ESM modules cannot be imported in CJS. Support for `postcss.config.mjs` landed [less than a year ago](https://github.com/postcss/postcss-load-config/blob/main/CHANGELOG.md#40-2022-05-23), there's probably quite a few people still using it; I don't want to cause unnecessary ecosystem churn. In any case, that would be best done as a separate refactor, after `async`.
