### ISSUE TITLE
postcss-import and gulp-sourcemaps

### ISSUE THREAD

**Issue by vkrol** [postcss/postcss-import#64]
Hello!

I try to combine postcss-import and gulp-sourcemaps plugins and I encounter a problem. I created the repository with the example code https://github.com/vkrol/imports-sourcemap
The problem is in the wrong "sources" entry in bundle.css.map https://github.com/vkrol/imports-sourcemap/blob/master/build/bundle.css.map

Please, help me. How i can fix this?

Thanks.

**Comment by MoOx** [comment]
I don't use sourcemap, but I think postcss is pretty good at it.
We currently have some tests for it. Seems related to https://github.com/cssnext/gulp-cssnext/issues/6

@ai postcss-import is just moving some node, this should not affect source (so sourcemap) right ?

**Comment by tgfjt** [comment]
:bell: I got same issue probably.

**Comment by zcoding** [comment]
same :joy_cat:

**Comment by RyanZim** [comment]
Does anyone still have this issue with the latest versions of everything?

**Comment by RyanZim** [comment]
I get the same results with the latest version.

@w0rm @ai Any ideas? I don't use gulp; is the gulpfile correct?

**Comment by ai** [comment]
It is `gulp-postcss` issue, as I understand. `postcss-import` doesn’t do anything with source maps, as I understand. But `gulp-postcss` could miss src → dest changes.

**Comment by w0rm** [comment]
@vkrol works without `{includeContent: false, sourceRoot: '/styles/'}` option, because `sourceRoot` path points to a wrong place.  Deleting the options works, it will include all the original sources into the source map, which is the recommended way.

If you really want to serve the sources from disk, then you have to pass the correct `sourceRoot`, that is  `../styles/bundles/`.

`../a.css` is relative to `bundle.css` in the sources, `bundle.css` is written to the `build` folder, so you need to go one level up, and then into the original path of `bundle.css`.

**Comment by vkrol** [comment]
@w0rm thanks!

**Comment by kittenlogic** [comment]
@w0rm  Thank You! Was having the same problem.
