### ISSUE TITLE
Please do not unpublish old versions from the NPM registry

### ISSUE THREAD

**Issue by moretti** [postcss/postcss-import#69]
Hi, I just noticed that `postcss-import@6.1.0` does not longer exist in the NPM registry. 
I suspect it is because you unpublished them from the registry.
Please don't do that, because it might break some workflows (i.e. `npm shrinkwrap`). 
Perhaps you can use `npm deprecate` instead?

**Comment by MoOx** [comment]
This release was online for a small time lapse and was a real fail by introducing a potential major breaking change for a lot of people that use sync postcss runner. https://github.com/postcss/postcss/issues/412
I decided to unpublish 6.1.0 the time a fix was been made. I prefer to annoy a small amount of people (like you) that use static version compared to people that don't really care about version (or just use default ^ caret version).

I am really sorry this happened and hope you understand the situation. I would be more careful in the future when merging/pushing pull request (because the introduced major breaking change was out of the scope of the PR and I didn't pay enough attention to it, my bad).

**Comment by moretti** [comment]
Fair enough, I would have used `npm deprecate` instead. 
Thank you for your quick response! :smile:
