### ISSUE TITLE
@import (multiple) '../../theme.config' less syntax support ?

### ISSUE THREAD

**Issue by kapouer** [postcss/postcss-import#71]
Hello,

there seems to be not much missing for semantic-ui to be built using postcss...
this seems to be a problem though:
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/button.less#L19

thanks for any advice on resolving this.

**Comment by MoOx** [comment]
Sorry I don't know less at all. Please en-light me what is this supposed to do. Thanks.

**Comment by kapouer** [comment]
documented here:
http://lesscss.org/features/#import-directives-feature

not sure yet why it uses this. The imported file contains only variables.
The syntax can be
@import (keyword1, keyword2) "foo.less";

**Comment by MoOx** [comment]
This seems a bit weird and a non standard syntax.

Also:
- reference: not doable and will break all plugins after
- inline: it's already the case since only plugins will "process" ast
- less: no comment
- css: same
- once: default behavior

Will be accepted as PR:

- multiple: can be implemented as an global option (related #67)
- optional: can be implemented as an global option

**Comment by kapouer** [comment]
semantic-ui uses this option because its build task concatenates then process all imports.
If it wasn't using nesting, the first import of the file would be enough...
But it does use `& {}` nesting everywhere, and it seems LESS (maybe SASS too) enforces nesting upon variables declarations too.

**Comment by MoOx** [comment]
Really sorry, but I don't understand how this make sense in postcss world. Each plugins can do multiple run. This one just "concatenate" imported files, other plugins have the responsibility to make several passes if needed (eg: postcss-custom-properties does 2 in order to read definitions and then resolve var())

**Comment by kapouer** [comment]
I was just investigating the issue here. The only point of concern for you is the (keyword) syntax, sorry for the confusion.

**Comment by MoOx** [comment]
You mean you want this plugin to accept this keyword (even if ignoring it) ?

**Comment by dehuszar** [comment]
I would also like to see `@import (reference) 'filename'` or some reasonable equivalent.  The ability to store all the rules as a variables to be extended as needed is invaluable and one of the primary reasons I use LESS over SASS.  MoOx, you say this won't work and break things.

Why is that?  Is it just that it is not a supported feature of the plugin, or that the functionality is impossible to recreate PostCSS?  I'm still wrapping my head around the API, CLI, and plugin system but it seems like it _should_ be possible, no?

**Comment by MoOx** [comment]
The (reference) does not make sense at all. PostCSS works with an AST. If you import something but do not add it to the AST, you are just not importing it. All plugins works on the AST and this plugin just add nodes to the AST. I don't see how this option can take sense in PostCSS.

**Comment by kapouer** [comment]
To better understand what a reference import is:
https://css-tricks.com/reference-imports-in-less-are-kinda-cool/
so you actually import parts of the file, with directives that are deeper in the AST.

**Comment by RyanZim** [comment]
This belongs in a separate plugin IMO.
